// Angular/Day03/demo/src/app/components/ReactiveForms/register/register.component.ts
import { Component } from '@angular/core';
import { FormGroup, FormControl, Validators } from '@angular/forms';

@Component({
  selector: 'app-register',
  templateUrl: './register.component.html',
  styleUrls: ['./register.component.css'],
})
export class RegisterComponent {
  registerForm = new FormGroup({
    username: new FormControl('', [
      Validators.required,
      Validators.minLength(4),
    ]),
    age: new FormControl(null, [Validators.required]),
  });

  get getUsername() {
    return this.registerForm.controls['username'];
  }

  get getAge() {
    return this.registerForm.controls['age'];
  }
  register(e: Event) {
    e.preventDefault();
    if (this.registerForm.status == 'VALID') {
      // connect
    } else {
      console.log('Has Error');
    }
  }
}

<div class="bg-light p-5">
  <div class="container">
    <div class="row">
      <form [formGroup]="registerForm" (submit)="register($event)">
        <div class="mb-3">
          <label for="exampleInputEmail1" class="form-label">User name</label>
          <input
            type="text"
            formControlName="username"
            class="form-control"
            placeholder="Enter username"
            id="exampleInputEmail1"
            aria-describedby="emailHelp"
          />
          <ng-container *ngIf="getUsername.touched">
            <div
              id="emailHelp"
              *ngIf="getUsername.hasError('required')"
              class="form-text text-danger"
            >
              username is required
            </div>
            <div
              id="emailHelp"
              *ngIf="getUsername.hasError('minlength')"
              class="form-text text-danger"
            >
              username length must be > 4
            </div>
          </ng-container>
        </div>
        <div class="mb-3">
          <label for="exampleInputPassword1" class="form-label">User age</label>
          <input
            formControlName="age"
            placeholder="Enter Your Age"
            type="number"
            class="form-control"
            id="exampleInputPassword1"
          />
          <div id="emailHelp" class="form-text text-danger">
            {{ getAge.errors | json }}
          </div>
        </div>

        <button type="submit" class="btn btn-dark">
          {{ false ? "Register" : "Login" }}
        </button>
        <p class="mt-4">
          {{ registerForm.value | json }}
        </p>
      </form>
    </div>
  </div>
</div>

// React/Day02/demo/src/component/Register.jsx
import React, { useState } from 'react'

export default function Register( props ) {

    let { formValues, setFormValues } = props



    // let [ username, setUsername ] = useState( '' )
    // let [ age, setAge ] = useState( '' )


    // let getUsernameValue = ( e ) => {
    //     setUsername( e.target.value )
    // }

    let getInputValue = ( e ) => {
        setFormValues( {
            ...formValues,
            [ e.target.name ]: e.target.value
        } )
    }

    // let getAgeValue = ( e ) => {
    //     setAge( e.target.value )
    // }

    let register = ( e ) => {
        e.preventDefault();

        console.log( formValues )
    }
    return (
        <div className='bg-dark text-light p-5 '>
            <h3>Register component</h3>
            <div className="container">
                <form onSubmit={register}>
                    <input value={formValues.username} onChange={getInputValue} type="text" className='form-control' name='username' placeholder='Enter Your Username' />

                    <input value={formValues.age} onChange={getInputValue} type="text" className='form-control mt-4' name='age' placeholder='Enter Your Age' />
                    <button className='btn btn-outline-warning mt-3'>Register</button>
                </form>
            </div>

        </div>
    )
}
