// React/Day04/demo/src/components/Products/Products.jsx
import React, { useEffect, useState } from 'react'
import { Table } from 'react-bootstrap';
import { NavLink } from 'react-router-dom';


import { getAllProducts } from '../../API/productsAPI';

export function Products() {

    let [ myList, setMyList ] = useState( [] )

    useEffect( () => {
        setMyList( getAllProducts() )
    }, [] )

    let productsList = myList.map( ( product ) => {
        return (

            <tr key={product.id}>
                <td>{product.id}</td>
                <td>{product.productName}</td>
                <td>{product.price}</td>
                <td>{product.quantity}</td>
                <td>
                    <NavLink to={`/products/${product.id}`} className='btn btn-outline-warning mx-1'>View Product</NavLink>
                    <button className='btn btn-outline-info mx-1'>Edit Product</button>
                    <button className='btn btn-outline-danger mx-1'>Delete Product</button>
                </td>
            </tr>
        )
    }
    )


    return (
        <div className='text-center bg-light p-5 mt-5 '>
            <h2 className='mb-5'>Our Products</h2>
            <div className="container">
                {myList.length == 0 ?
                    <h1>No products To show</h1> :
                    <Table striped bordered hover>
                        <thead>
                            <tr>
                                <th>Id</th>
                                <th>Product Name</th>
                                <th>Product Price</th>
                                <th>Product Quantity</th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            {productsList}
                        </tbody>
                    </Table>
                }
            </div>
        </div>
    )
}

// Angular/Day04/demo/src/app/components/products/products.component.ts
import { Component, OnInit } from '@angular/core';
import { Iproduct } from 'src/app/models/iproduct';
import { ProductsList } from 'src/app/models/productsList';
import { ProductService } from 'src/app/services/product.service';
import { ProductwithAPIService } from 'src/app/services/productwith-api.service';

@Component({
  selector: 'app-products',
  templateUrl: './products.component.html',
  styleUrls: ['./products.component.css'],
})
export class ProductsComponent implements OnInit {
  products: Iproduct[] = [];
  constructor(private productServices: ProductwithAPIService) {}
  ngOnInit(): void {
    this.productServices.getAllProducts().subscribe({
      next: (myProducts: Iproduct[]) => {
        this.products = myProducts;
      },
    });
  }
}

<div class="container mt-5">
  <div class="row">
    <table class="table">
      <thead>
        <tr>
          <th scope="col">Id</th>
          <th scope="col">Product Name</th>
          <th scope="col">Product Price</th>
          <th scope="col">Product quantity</th>
          <th scope="col">Actions</th>
        </tr>
      </thead>
      <tbody>
        <tr *ngFor="let product of products">
          <th scope="row">{{ product.id }}</th>
          <td>{{ product.productName }}</td>
          <td>{{ product.price }}</td>
          <td>{{ product.quantity }}</td>
          <td>
            <i
              [routerLink]="['/products', product.id, 'edit']"
              class="mx-1 fs-4 text-info bi bi-pencil-square"
            ></i>
            <i
              [routerLink]="['/products', product.id]"
              class="mx-1 fs-4 text-warning bi bi-eye-fill"
            ></i>
            <i class="mx-1 fs-4 text-danger bi bi-trash3"></i>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</div>
