// Angular/Day04/demo/src/app/components/products/product-form/product-form.component.ts
import { Component, OnInit } from '@angular/core';
import { Router, ActivatedRoute } from '@angular/router';
import { FormGroup, FormControl } from '@angular/forms';
import { ProductwithAPIService } from 'src/app/services/productwith-api.service';
import { Iproduct } from 'src/app/models/iproduct';

@Component({
  selector: 'app-product-form',
  templateUrl: './product-form.component.html',
  styleUrls: ['./product-form.component.css'],
})
export class ProductFormComponent implements OnInit {
  productId: any;
  product: any;

  constructor(
    private router: Router,
    private activatedRoute: ActivatedRoute,
    private productServices: ProductwithAPIService
  ) {}

  ngOnInit(): void {
    // this.productId = this.activatedRoute.snapshot.params['id'];
    this.activatedRoute.params.subscribe({
      next: (params) => {
        this.productId = params['id'];
        this.getProductName.setValue('');
        this.getProductPrice.setValue(null);
        this.getProductQuantity.setValue(null);
      },
    });
    if (this.productId != 0) {
      this.productServices.getProductById(this.productId).subscribe({
        next: (myProduct: Iproduct) => {
          this.product = myProduct;

          this.getProductName.setValue(this.product.productName);
          this.getProductPrice.setValue(this.product.price);
          this.getProductQuantity.setValue(this.product.quantity);
        },
      });
    }
  }

  productForm = new FormGroup({
    productName: new FormControl(),
    price: new FormControl(),
    quantity: new FormControl(),
  });

  get getProductName() {
    return this.productForm.controls['productName'];
  }
  get getProductPrice() {
    return this.productForm.controls['price'];
  }
  get getProductQuantity() {
    return this.productForm.controls['quantity'];
  }
  formOperation(e: Event) {
    e.preventDefault();

    if (this.productId == 0) {
      this.productServices.addNewProduct(this.productForm.value).subscribe();
    } else {
      // edit
      this.productServices
        .editProduct(this.productId, this.productForm.value)
        .subscribe();
    }
    this.router.navigate(['/products']);
  }
}

<div class="container mt-5">
  <h1 class="mx-5">
    {{ productId == 0 ? "Add New Product" : "Edit Product" }}
  </h1>
  <form [formGroup]="productForm" (submit)="formOperation($event)">
    <div class="mb-3">
      <label for="exampleInputEmail1" class="form-label">Product Name</label>
      <input
        type="text"
        class="form-control"
        id="exampleInputEmail1"
        placeholder="Enter Product Name"
        aria-describedby="emailHelp"
        formControlName="productName"
      />
      <div id="emailHelp" class="form-text">
        We'll never share your email with anyone else.
      </div>
    </div>
    <div class="mb-3">
      <label for="exampleInputPassword1" class="form-label"
        >Product Price</label
      >
      <input
        type="number"
        placeholder="Enter Product Price"
        class="form-control"
        id="exampleInputPassword1"
        formControlName="price"
      />
    </div>
    <div class="mb-3">
      <label for="exampleInputPassword1" class="form-label"
        >Product Quantity</label
      >
      <input
        type="number"
        placeholder="Enter Product Quantity"
        class="form-control"
        id="exampleInputPassword1"
        formControlName="quantity"
      />
    </div>

    <button type="submit" class="btn btn-success">
      {{ productId == 0 ? "Add New Product" : "Edit Product" }}
    </button>
  </form>
</div>

// React/Day04/demo/src/components/Products/ProductForm.jsx
import React, { useState } from 'react'
import { addNewProduct } from '../../API/productsAPI'
import { useNavigate } from 'react-router-dom';
export function ProductForm() {

    let navigate = useNavigate();

    let [ formsValues, setFormsValues ] = useState( {
        productName: '',
        price: '',
        quantity: ''
    } );


    let getInputValue = ( e ) => {
        setFormsValues( {
            ...formsValues,
            [ e.target.name ]: e.target.value
        } )

    }
    let formOperation = ( e ) => {
        e.preventDefault();
        addNewProduct( formsValues )
        navigate( '/products' )

    }
    return (
        <div className='bg-light p-5 mt-5 '>
            <div className="container">
                <h1>Add New Product</h1>
                <form onSubmit={formOperation} >
                    <input onChange={getInputValue} value={formsValues.productName} name="productName" type="text" placeholder='Enter Product Name' className='form-control mb-3' />
                    <input onChange={getInputValue} value={formsValues.price} name='price' type="text" placeholder='Enter Product Price' className='form-control mb-3' />
                    <input onChange={getInputValue} value={formsValues.quantity} name="quantity" type="text" placeholder='Enter Product Quantity' className='form-control mb-3' />
                    <button className='btn btn-outline-success'>Add New Product</button>
                </form>
            </div>

        </div>
    )
}
